# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx
language: swift
osx_image: xcode10.2
script: set -o pipefail && xcodebuild -scheme Workbench PROVISIONING_PROFILE="" DEVELOPMENT_TEAM="" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
